// Package v1alpha1openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1alpha1openapi

import (
	"encoding/json"
	"time"
)

// Defines values for AffectedTargetEffectType.
const (
	AffectedTargetEffectTypeDeleted   AffectedTargetEffectType = "deleted"
	AffectedTargetEffectTypeDisrupted AffectedTargetEffectType = "disrupted"
	AffectedTargetEffectTypeModified  AffectedTargetEffectType = "modified"
	AffectedTargetEffectTypeOrphaned  AffectedTargetEffectType = "orphaned"
)

// Valid indicates whether the value is a known member of the AffectedTargetEffectType enum.
func (e AffectedTargetEffectType) Valid() bool {
	switch e {
	case AffectedTargetEffectTypeDeleted:
		return true
	case AffectedTargetEffectTypeDisrupted:
		return true
	case AffectedTargetEffectTypeModified:
		return true
	case AffectedTargetEffectTypeOrphaned:
		return true
	default:
		return false
	}
}

// Defines values for AgentRequestDTOExecutionMode.
const (
	AgentRequestDTOExecutionModeSingle AgentRequestDTOExecutionMode = "single"
	AgentRequestDTOExecutionModeScoped AgentRequestDTOExecutionMode = "scoped"
)

// Valid indicates whether the value is a known member of the AgentRequestDTOExecutionMode enum.
func (e AgentRequestDTOExecutionMode) Valid() bool {
	switch e {
	case AgentRequestDTOExecutionModeSingle:
		return true
	case AgentRequestDTOExecutionModeScoped:
		return true
	default:
		return false
	}
}

// Defines values for AgentRequestDTOPhase.
const (
	AgentRequestDTOPhaseApproved        AgentRequestDTOPhase = "Approved"
	AgentRequestDTOPhaseAwaitingVerdict AgentRequestDTOPhase = "AwaitingVerdict"
	AgentRequestDTOPhaseCompleted       AgentRequestDTOPhase = "Completed"
	AgentRequestDTOPhaseDenied          AgentRequestDTOPhase = "Denied"
	AgentRequestDTOPhaseExecuting       AgentRequestDTOPhase = "Executing"
	AgentRequestDTOPhaseExpired         AgentRequestDTOPhase = "Expired"
	AgentRequestDTOPhaseFailed          AgentRequestDTOPhase = "Failed"
	AgentRequestDTOPhasePending         AgentRequestDTOPhase = "Pending"
)

// Valid indicates whether the value is a known member of the AgentRequestDTOPhase enum.
func (e AgentRequestDTOPhase) Valid() bool {
	switch e {
	case AgentRequestDTOPhaseApproved:
		return true
	case AgentRequestDTOPhaseAwaitingVerdict:
		return true
	case AgentRequestDTOPhaseCompleted:
		return true
	case AgentRequestDTOPhaseDenied:
		return true
	case AgentRequestDTOPhaseExecuting:
		return true
	case AgentRequestDTOPhaseExpired:
		return true
	case AgentRequestDTOPhaseFailed:
		return true
	case AgentRequestDTOPhasePending:
		return true
	default:
		return false
	}
}

// Defines values for CascadeModelModelSourceTrust.
const (
	CascadeModelModelSourceTrustAuthoritative CascadeModelModelSourceTrust = "authoritative"
	CascadeModelModelSourceTrustDerived       CascadeModelModelSourceTrust = "derived"
	CascadeModelModelSourceTrustInferred      CascadeModelModelSourceTrust = "inferred"
)

// Valid indicates whether the value is a known member of the CascadeModelModelSourceTrust enum.
func (e CascadeModelModelSourceTrust) Valid() bool {
	switch e {
	case CascadeModelModelSourceTrustAuthoritative:
		return true
	case CascadeModelModelSourceTrustDerived:
		return true
	case CascadeModelModelSourceTrustInferred:
		return true
	default:
		return false
	}
}

// Defines values for ConditionStatus.
const (
	ConditionStatusFalse   ConditionStatus = "False"
	ConditionStatusTrue    ConditionStatus = "True"
	ConditionStatusUnknown ConditionStatus = "Unknown"
)

// Defines values for CreateAgentRequestRequestExecutionMode.
const (
	CreateAgentRequestRequestExecutionModeSingle CreateAgentRequestRequestExecutionMode = "single"
	CreateAgentRequestRequestExecutionModeScoped CreateAgentRequestRequestExecutionMode = "scoped"
)

// Defines values for SubmitVerdictRequestVerdict.
const (
	SubmitVerdictRequestVerdictCorrect   SubmitVerdictRequestVerdict = "correct"
	SubmitVerdictRequestVerdictIncorrect SubmitVerdictRequestVerdict = "incorrect"
	SubmitVerdictRequestVerdictPartial   SubmitVerdictRequestVerdict = "partial"
)

// Valid indicates whether the value is a known member of the SubmitVerdictRequestVerdict enum.
func (e SubmitVerdictRequestVerdict) Valid() bool {
	switch e {
	case SubmitVerdictRequestVerdictCorrect:
		return true
	case SubmitVerdictRequestVerdictIncorrect:
		return true
	case SubmitVerdictRequestVerdictPartial:
		return true
	default:
		return false
	}
}

// Defines values for SubmitVerdictRequestReasonCode.
const (
	SubmitVerdictRequestReasonCodeWrongDiagnosis SubmitVerdictRequestReasonCode = "wrong_diagnosis"
	SubmitVerdictRequestReasonCodeBadTiming      SubmitVerdictRequestReasonCode = "bad_timing"
	SubmitVerdictRequestReasonCodeScopeTooBroad  SubmitVerdictRequestReasonCode = "scope_too_broad"
	SubmitVerdictRequestReasonCodePrecautionary  SubmitVerdictRequestReasonCode = "precautionary"
	SubmitVerdictRequestReasonCodePolicyBlock    SubmitVerdictRequestReasonCode = "policy_block"
)

// Valid indicates whether the value is a known member of the SubmitVerdictRequestReasonCode enum.
func (e SubmitVerdictRequestReasonCode) Valid() bool {
	switch e {
	case SubmitVerdictRequestReasonCodeWrongDiagnosis:
		return true
	case SubmitVerdictRequestReasonCodeBadTiming:
		return true
	case SubmitVerdictRequestReasonCodeScopeTooBroad:
		return true
	case SubmitVerdictRequestReasonCodePrecautionary:
		return true
	case SubmitVerdictRequestReasonCodePolicyBlock:
		return true
	default:
		return false
	}
}

// Defines values for TransitionPhaseRequestTargetPhase.
const (
	TransitionPhaseRequestTargetPhaseApproved  TransitionPhaseRequestTargetPhase = "Approved"
	TransitionPhaseRequestTargetPhaseCompleted TransitionPhaseRequestTargetPhase = "Completed"
	TransitionPhaseRequestTargetPhaseDenied    TransitionPhaseRequestTargetPhase = "Denied"
	TransitionPhaseRequestTargetPhaseExecuting TransitionPhaseRequestTargetPhase = "Executing"
)

// Valid indicates whether the value is a known member of the TransitionPhaseRequestTargetPhase enum.
func (e TransitionPhaseRequestTargetPhase) Valid() bool {
	switch e {
	case TransitionPhaseRequestTargetPhaseApproved:
		return true
	case TransitionPhaseRequestTargetPhaseCompleted:
		return true
	case TransitionPhaseRequestTargetPhaseDenied:
		return true
	case TransitionPhaseRequestTargetPhaseExecuting:
		return true
	default:
		return false
	}
}

// Defines values for VerdictInfoVerdict.
const (
	VerdictInfoVerdictCorrect   VerdictInfoVerdict = "correct"
	VerdictInfoVerdictIncorrect VerdictInfoVerdict = "incorrect"
	VerdictInfoVerdictPartial   VerdictInfoVerdict = "partial"
)

// Defines values for VerdictInfoReasonCode.
const (
	VerdictInfoReasonCodeWrongDiagnosis VerdictInfoReasonCode = "wrong_diagnosis"
	VerdictInfoReasonCodeBadTiming      VerdictInfoReasonCode = "bad_timing"
	VerdictInfoReasonCodeScopeTooBroad  VerdictInfoReasonCode = "scope_too_broad"
	VerdictInfoReasonCodePrecautionary  VerdictInfoReasonCode = "precautionary"
	VerdictInfoReasonCodePolicyBlock    VerdictInfoReasonCode = "policy_block"
)

// AffectedTarget defines model for AffectedTarget.
type AffectedTarget struct {
	EffectType AffectedTargetEffectType `json:"effectType"`
	URI        string                   `json:"uri"`
}

// AffectedTargetEffectType defines model for AffectedTarget.EffectType.
type AffectedTargetEffectType string

// AgentRequestDTO defines model for AgentRequestDTO.
type AgentRequestDTO struct {
	Action        string    `json:"action"`
	AgentIdentity string    `json:"agentIdentity"`
	CascadeModel  *CascadeModel `json:"cascadeModel,omitempty"`
	Classification *string  `json:"classification,omitempty"`
	Conditions    *[]Condition `json:"conditions,omitempty"`
	ControlPlaneVerification *ControlPlaneVerification `json:"controlPlaneVerification,omitempty"`
	CorrelationID *string   `json:"correlationID,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	Denial        *DenialResponse `json:"denial,omitempty"`
	ExecutionMode *AgentRequestDTOExecutionMode `json:"executionMode,omitempty"`
	GovernedResourceRef *GovernedResourceRef `json:"governedResourceRef,omitempty"`
	IntentPlanRef *string  `json:"intentPlanRef,omitempty"`
	Interruptibility *bool `json:"interruptibility,omitempty"`

	// Name Kubernetes object name (server-generated)
	Name string `json:"name"`
	Namespace string `json:"namespace"`

	// Parameters Action-specific parameters (any JSON value)
	Parameters     *json.RawMessage `json:"parameters,omitempty"`
	Phase          AgentRequestDTOPhase `json:"phase"`
	Priority       *int32           `json:"priority,omitempty"`
	Reason         string           `json:"reason"`
	ReasoningTrace *ReasoningTrace  `json:"reasoningTrace,omitempty"`
	ScopeBounds    *ScopeBounds     `json:"scopeBounds,omitempty"`
	Target         Target           `json:"target"`
	Verdict        *VerdictInfo     `json:"verdict,omitempty"`
}

// AgentRequestDTOExecutionMode defines model for AgentRequestDTO.ExecutionMode.
type AgentRequestDTOExecutionMode string

// AgentRequestDTOPhase defines model for AgentRequestDTO.Phase.
type AgentRequestDTOPhase string

// AgentRequestList defines model for AgentRequestList.
type AgentRequestList struct {
	Items []AgentRequestDTO `json:"items"`

	// NextPageToken Opaque pagination token; present only when more items exist
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// CascadeModel defines model for CascadeModel.
type CascadeModel struct {
	AffectedTargets  *[]AffectedTarget             `json:"affectedTargets,omitempty"`
	ModelSourceID    *string                        `json:"modelSourceID,omitempty"`
	ModelSourceTrust *CascadeModelModelSourceTrust  `json:"modelSourceTrust,omitempty"`
}

// CascadeModelModelSourceTrust defines model for CascadeModel.ModelSourceTrust.
type CascadeModelModelSourceTrust string

// Condition defines model for Condition.
type Condition struct {
	LastTransitionTime time.Time       `json:"lastTransitionTime"`
	Message            string          `json:"message"`
	Reason             string          `json:"reason"`
	Status             ConditionStatus `json:"status"`
	Type               string          `json:"type"`
}

// ConditionStatus defines model for Condition.Status.
type ConditionStatus string

// ControlPlaneVerification defines model for ControlPlaneVerification.
type ControlPlaneVerification struct {
	ActiveEndpointCount       *int       `json:"activeEndpointCount,omitempty"`
	DownstreamServices        *[]string  `json:"downstreamServices,omitempty"`
	EvaluatedStateFingerprint *string    `json:"evaluatedStateFingerprint,omitempty"`
	FetchedAt                 *time.Time `json:"fetchedAt,omitempty"`
	HasActiveEndpoints        *bool      `json:"hasActiveEndpoints,omitempty"`
	ReadyReplicas             *int       `json:"readyReplicas,omitempty"`
	SpecReplicas              *int       `json:"specReplicas,omitempty"`
	TargetExists              *bool      `json:"targetExists,omitempty"`
}

// CreateAgentRequestRequest defines model for CreateAgentRequestRequest.
type CreateAgentRequestRequest struct {
	Action         string  `json:"action"`
	AgentIdentity  string  `json:"agentIdentity"`
	CascadeModel   *CascadeModel `json:"cascadeModel,omitempty"`
	Classification *string `json:"classification,omitempty"`
	CorrelationID  *string `json:"correlationID,omitempty"`
	ExecutionMode  *CreateAgentRequestRequestExecutionMode `json:"executionMode,omitempty"`
	IntentPlanRef  *string `json:"intentPlanRef,omitempty"`
	Interruptibility *bool `json:"interruptibility,omitempty"`

	// Parameters Action-specific parameters (any JSON value)
	Parameters     *json.RawMessage `json:"parameters,omitempty"`
	Priority       *int32           `json:"priority,omitempty"`
	Reason         string           `json:"reason"`
	ReasoningTrace *ReasoningTrace  `json:"reasoningTrace,omitempty"`
	ScopeBounds    *ScopeBounds     `json:"scopeBounds,omitempty"`
	Target         Target           `json:"target"`
}

// CreateAgentRequestRequestExecutionMode defines model for CreateAgentRequestRequest.ExecutionMode.
type CreateAgentRequestRequestExecutionMode string

// DenialResponse defines model for DenialResponse.
type DenialResponse struct {
	Code              *string         `json:"code,omitempty"`
	Message           *string         `json:"message,omitempty"`
	PolicyResults     *[]PolicyResult `json:"policyResults,omitempty"`
	RetryAfterSeconds *int32          `json:"retryAfterSeconds,omitempty"`
}

// GovernedResourceRef defines model for GovernedResourceRef.
type GovernedResourceRef struct {
	Generation *int64  `json:"generation,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// PolicyResult defines model for PolicyResult.
type PolicyResult struct {
	PolicyGeneration *int64  `json:"policyGeneration,omitempty"`
	PolicyName       *string `json:"policyName,omitempty"`
	Result           *string `json:"result,omitempty"`
	RuleName         *string `json:"ruleName,omitempty"`
}

// ReasoningTrace defines model for ReasoningTrace.
type ReasoningTrace struct {
	Alternatives        *[]string           `json:"alternatives,omitempty"`
	ComponentConfidence *map[string]float64 `json:"componentConfidence,omitempty"`
	ConfidenceScore     *float64            `json:"confidenceScore,omitempty"`
	TraceReference      *string             `json:"traceReference,omitempty"`
}

// ScopeBounds defines model for ScopeBounds.
type ScopeBounds struct {
	PermittedActions        []string `json:"permittedActions"`
	PermittedTargetPatterns []string `json:"permittedTargetPatterns"`
	TimeBoundSeconds        int32    `json:"timeBoundSeconds"`
}

// SubmitVerdictRequest defines model for SubmitVerdictRequest.
type SubmitVerdictRequest struct {
	Note       *string                        `json:"note,omitempty"`
	ReasonCode *SubmitVerdictRequestReasonCode `json:"reasonCode,omitempty"`
	Verdict    SubmitVerdictRequestVerdict     `json:"verdict"`
}

// SubmitVerdictRequestReasonCode defines model for SubmitVerdictRequest.ReasonCode.
type SubmitVerdictRequestReasonCode string

// SubmitVerdictRequestVerdict defines model for SubmitVerdictRequest.Verdict.
type SubmitVerdictRequestVerdict string

// Target defines model for Target.
type Target struct {
	Attributes   *map[string]string `json:"attributes,omitempty"`
	ResourceType *string            `json:"resourceType,omitempty"`
	URI          string             `json:"uri"`
}

// TransitionPhaseRequest defines model for TransitionPhaseRequest.
type TransitionPhaseRequest struct {
	Reason      *string                           `json:"reason,omitempty"`
	TargetPhase TransitionPhaseRequestTargetPhase `json:"targetPhase"`
}

// TransitionPhaseRequestTargetPhase defines model for TransitionPhaseRequest.TargetPhase.
type TransitionPhaseRequestTargetPhase string

// VerdictInfo defines model for VerdictInfo.
type VerdictInfo struct {
	At *time.Time `json:"at,omitempty"`

	// By Set server-side from the authenticated caller identity
	By         *string            `json:"by,omitempty"`
	Note       *string            `json:"note,omitempty"`
	ReasonCode *VerdictInfoReasonCode `json:"reasonCode,omitempty"`
	Verdict    *VerdictInfoVerdict `json:"verdict,omitempty"`
}

// VerdictInfoReasonCode defines model for VerdictInfo.ReasonCode.
type VerdictInfoReasonCode string

// VerdictInfoVerdict defines model for VerdictInfo.Verdict.
type VerdictInfoVerdict string

// CreateAgentRequestJSONRequestBody defines body for CreateAgentRequest for application/json ContentType.
type CreateAgentRequestJSONRequestBody = CreateAgentRequestRequest

// TransitionAgentRequestPhaseJSONRequestBody defines body for TransitionAgentRequestPhase for application/json ContentType.
type TransitionAgentRequestPhaseJSONRequestBody = TransitionPhaseRequest

// SubmitAgentRequestVerdictJSONRequestBody defines body for SubmitAgentRequestVerdict for application/json ContentType.
type SubmitAgentRequestVerdictJSONRequestBody = SubmitVerdictRequest
