FROM golang:1.25 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o dashboard ./cmd/dashboard

FROM gcr.io/distroless/static:nonroot
WORKDIR /

COPY --from=builder /workspace/dashboard .
COPY --from=builder /workspace/cmd/dashboard/app.js     /cmd/dashboard/app.js
COPY --from=builder /workspace/cmd/dashboard/index.html /cmd/dashboard/index.html
COPY --from=builder /workspace/cmd/dashboard/styles.css /cmd/dashboard/styles.css

USER 65532:65532

ENTRYPOINT ["/dashboard", "--static-dir", "/cmd/dashboard"]
